/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentPortalRouteImport } from './routes/student-portal'
import { Route as StudentLifeRouteImport } from './routes/student-life'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ParentPortalRouteImport } from './routes/parent-portal'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as AcademicsSecondaryRouteImport } from './routes/academics.secondary'
import { Route as AcademicsPrimaryRouteImport } from './routes/academics.primary'
import { Route as AcademicsNurseryRouteImport } from './routes/academics.nursery'
import { Route as AuthenticatedDashboardTeacherRouteImport } from './routes/_authenticated/dashboard.teacher'
import { Route as AuthenticatedDashboardSuperAdminRouteImport } from './routes/_authenticated/dashboard.super-admin'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard.student'
import { Route as AuthenticatedDashboardSchoolAdminRouteImport } from './routes/_authenticated/dashboard.school-admin'
import { Route as AuthenticatedDashboardPendingRouteImport } from './routes/_authenticated/dashboard.pending'
import { Route as AuthenticatedDashboardParentRouteImport } from './routes/_authenticated/dashboard.parent'
import { Route as AuthenticatedDashboardLibrarianRouteImport } from './routes/_authenticated/dashboard.librarian'
import { Route as AuthenticatedDashboardAccountantRouteImport } from './routes/_authenticated/dashboard.accountant'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'
import { Route as AuthenticatedDashboardPaymentCallbackRouteImport } from './routes/_authenticated/dashboard.payment.callback'

const StudentPortalRoute = StudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLifeRoute = StudentLifeRouteImport.update({
  id: '/student-life',
  path: '/student-life',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentPortalRoute = ParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/academics/',
  path: '/academics/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsSecondaryRoute = AcademicsSecondaryRouteImport.update({
  id: '/academics/secondary',
  path: '/academics/secondary',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsPrimaryRoute = AcademicsPrimaryRouteImport.update({
  id: '/academics/primary',
  path: '/academics/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsNurseryRoute = AcademicsNurseryRouteImport.update({
  id: '/academics/nursery',
  path: '/academics/nursery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardTeacherRoute =
  AuthenticatedDashboardTeacherRouteImport.update({
    id: '/dashboard/teacher',
    path: '/dashboard/teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSuperAdminRoute =
  AuthenticatedDashboardSuperAdminRouteImport.update({
    id: '/dashboard/super-admin',
    path: '/dashboard/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSchoolAdminRoute =
  AuthenticatedDashboardSchoolAdminRouteImport.update({
    id: '/dashboard/school-admin',
    path: '/dashboard/school-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPendingRoute =
  AuthenticatedDashboardPendingRouteImport.update({
    id: '/dashboard/pending',
    path: '/dashboard/pending',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardParentRoute =
  AuthenticatedDashboardParentRouteImport.update({
    id: '/dashboard/parent',
    path: '/dashboard/parent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardLibrarianRoute =
  AuthenticatedDashboardLibrarianRouteImport.update({
    id: '/dashboard/librarian',
    path: '/dashboard/librarian',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAccountantRoute =
  AuthenticatedDashboardAccountantRouteImport.update({
    id: '/dashboard/accountant',
    path: '/dashboard/accountant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardPaymentCallbackRoute =
  AuthenticatedDashboardPaymentCallbackRouteImport.update({
    id: '/dashboard/payment/callback',
    path: '/dashboard/payment/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-portal': typeof ParentPortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-life': typeof StudentLifeRoute
  '/student-portal': typeof StudentPortalRoute
  '/academics/nursery': typeof AcademicsNurseryRoute
  '/academics/primary': typeof AcademicsPrimaryRoute
  '/academics/secondary': typeof AcademicsSecondaryRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/academics/': typeof AcademicsIndexRoute
  '/dashboard/accountant': typeof AuthenticatedDashboardAccountantRoute
  '/dashboard/librarian': typeof AuthenticatedDashboardLibrarianRoute
  '/dashboard/parent': typeof AuthenticatedDashboardParentRoute
  '/dashboard/pending': typeof AuthenticatedDashboardPendingRoute
  '/dashboard/school-admin': typeof AuthenticatedDashboardSchoolAdminRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/dashboard/teacher': typeof AuthenticatedDashboardTeacherRoute
  '/dashboard/payment/callback': typeof AuthenticatedDashboardPaymentCallbackRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-portal': typeof ParentPortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-life': typeof StudentLifeRoute
  '/student-portal': typeof StudentPortalRoute
  '/academics/nursery': typeof AcademicsNurseryRoute
  '/academics/primary': typeof AcademicsPrimaryRoute
  '/academics/secondary': typeof AcademicsSecondaryRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/academics': typeof AcademicsIndexRoute
  '/dashboard/accountant': typeof AuthenticatedDashboardAccountantRoute
  '/dashboard/librarian': typeof AuthenticatedDashboardLibrarianRoute
  '/dashboard/parent': typeof AuthenticatedDashboardParentRoute
  '/dashboard/pending': typeof AuthenticatedDashboardPendingRoute
  '/dashboard/school-admin': typeof AuthenticatedDashboardSchoolAdminRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/dashboard/teacher': typeof AuthenticatedDashboardTeacherRoute
  '/dashboard/payment/callback': typeof AuthenticatedDashboardPaymentCallbackRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/parent-portal': typeof ParentPortalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-life': typeof StudentLifeRoute
  '/student-portal': typeof StudentPortalRoute
  '/academics/nursery': typeof AcademicsNurseryRoute
  '/academics/primary': typeof AcademicsPrimaryRoute
  '/academics/secondary': typeof AcademicsSecondaryRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/academics/': typeof AcademicsIndexRoute
  '/_authenticated/dashboard/accountant': typeof AuthenticatedDashboardAccountantRoute
  '/_authenticated/dashboard/librarian': typeof AuthenticatedDashboardLibrarianRoute
  '/_authenticated/dashboard/parent': typeof AuthenticatedDashboardParentRoute
  '/_authenticated/dashboard/pending': typeof AuthenticatedDashboardPendingRoute
  '/_authenticated/dashboard/school-admin': typeof AuthenticatedDashboardSchoolAdminRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/dashboard/super-admin': typeof AuthenticatedDashboardSuperAdminRoute
  '/_authenticated/dashboard/teacher': typeof AuthenticatedDashboardTeacherRoute
  '/_authenticated/dashboard/payment/callback': typeof AuthenticatedDashboardPaymentCallbackRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/parent-portal'
    | '/reset-password'
    | '/set-password'
    | '/sitemap.xml'
    | '/student-life'
    | '/student-portal'
    | '/academics/nursery'
    | '/academics/primary'
    | '/academics/secondary'
    | '/payment/callback'
    | '/academics/'
    | '/dashboard/accountant'
    | '/dashboard/librarian'
    | '/dashboard/parent'
    | '/dashboard/pending'
    | '/dashboard/school-admin'
    | '/dashboard/student'
    | '/dashboard/super-admin'
    | '/dashboard/teacher'
    | '/dashboard/payment/callback'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/parent-portal'
    | '/reset-password'
    | '/set-password'
    | '/sitemap.xml'
    | '/student-life'
    | '/student-portal'
    | '/academics/nursery'
    | '/academics/primary'
    | '/academics/secondary'
    | '/payment/callback'
    | '/academics'
    | '/dashboard/accountant'
    | '/dashboard/librarian'
    | '/dashboard/parent'
    | '/dashboard/pending'
    | '/dashboard/school-admin'
    | '/dashboard/student'
    | '/dashboard/super-admin'
    | '/dashboard/teacher'
    | '/dashboard/payment/callback'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/faq'
    | '/gallery'
    | '/news'
    | '/parent-portal'
    | '/reset-password'
    | '/set-password'
    | '/sitemap.xml'
    | '/student-life'
    | '/student-portal'
    | '/academics/nursery'
    | '/academics/primary'
    | '/academics/secondary'
    | '/payment/callback'
    | '/academics/'
    | '/_authenticated/dashboard/accountant'
    | '/_authenticated/dashboard/librarian'
    | '/_authenticated/dashboard/parent'
    | '/_authenticated/dashboard/pending'
    | '/_authenticated/dashboard/school-admin'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/dashboard/super-admin'
    | '/_authenticated/dashboard/teacher'
    | '/_authenticated/dashboard/payment/callback'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  ParentPortalRoute: typeof ParentPortalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentLifeRoute: typeof StudentLifeRoute
  StudentPortalRoute: typeof StudentPortalRoute
  AcademicsNurseryRoute: typeof AcademicsNurseryRoute
  AcademicsPrimaryRoute: typeof AcademicsPrimaryRoute
  AcademicsSecondaryRoute: typeof AcademicsSecondaryRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-portal': {
      id: '/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof StudentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-life': {
      id: '/student-life'
      path: '/student-life'
      fullPath: '/student-life'
      preLoaderRoute: typeof StudentLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-portal': {
      id: '/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof ParentPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/': {
      id: '/academics/'
      path: '/academics'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/secondary': {
      id: '/academics/secondary'
      path: '/academics/secondary'
      fullPath: '/academics/secondary'
      preLoaderRoute: typeof AcademicsSecondaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/primary': {
      id: '/academics/primary'
      path: '/academics/primary'
      fullPath: '/academics/primary'
      preLoaderRoute: typeof AcademicsPrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics/nursery': {
      id: '/academics/nursery'
      path: '/academics/nursery'
      fullPath: '/academics/nursery'
      preLoaderRoute: typeof AcademicsNurseryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/teacher': {
      id: '/_authenticated/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof AuthenticatedDashboardTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/super-admin': {
      id: '/_authenticated/dashboard/super-admin'
      path: '/dashboard/super-admin'
      fullPath: '/dashboard/super-admin'
      preLoaderRoute: typeof AuthenticatedDashboardSuperAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/school-admin': {
      id: '/_authenticated/dashboard/school-admin'
      path: '/dashboard/school-admin'
      fullPath: '/dashboard/school-admin'
      preLoaderRoute: typeof AuthenticatedDashboardSchoolAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/pending': {
      id: '/_authenticated/dashboard/pending'
      path: '/dashboard/pending'
      fullPath: '/dashboard/pending'
      preLoaderRoute: typeof AuthenticatedDashboardPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/parent': {
      id: '/_authenticated/dashboard/parent'
      path: '/dashboard/parent'
      fullPath: '/dashboard/parent'
      preLoaderRoute: typeof AuthenticatedDashboardParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/librarian': {
      id: '/_authenticated/dashboard/librarian'
      path: '/dashboard/librarian'
      fullPath: '/dashboard/librarian'
      preLoaderRoute: typeof AuthenticatedDashboardLibrarianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/accountant': {
      id: '/_authenticated/dashboard/accountant'
      path: '/dashboard/accountant'
      fullPath: '/dashboard/accountant'
      preLoaderRoute: typeof AuthenticatedDashboardAccountantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/payment/callback': {
      id: '/_authenticated/dashboard/payment/callback'
      path: '/dashboard/payment/callback'
      fullPath: '/dashboard/payment/callback'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardAccountantRoute: typeof AuthenticatedDashboardAccountantRoute
  AuthenticatedDashboardLibrarianRoute: typeof AuthenticatedDashboardLibrarianRoute
  AuthenticatedDashboardParentRoute: typeof AuthenticatedDashboardParentRoute
  AuthenticatedDashboardPendingRoute: typeof AuthenticatedDashboardPendingRoute
  AuthenticatedDashboardSchoolAdminRoute: typeof AuthenticatedDashboardSchoolAdminRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedDashboardSuperAdminRoute: typeof AuthenticatedDashboardSuperAdminRoute
  AuthenticatedDashboardTeacherRoute: typeof AuthenticatedDashboardTeacherRoute
  AuthenticatedDashboardPaymentCallbackRoute: typeof AuthenticatedDashboardPaymentCallbackRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardAccountantRoute: AuthenticatedDashboardAccountantRoute,
  AuthenticatedDashboardLibrarianRoute: AuthenticatedDashboardLibrarianRoute,
  AuthenticatedDashboardParentRoute: AuthenticatedDashboardParentRoute,
  AuthenticatedDashboardPendingRoute: AuthenticatedDashboardPendingRoute,
  AuthenticatedDashboardSchoolAdminRoute:
    AuthenticatedDashboardSchoolAdminRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedDashboardSuperAdminRoute: AuthenticatedDashboardSuperAdminRoute,
  AuthenticatedDashboardTeacherRoute: AuthenticatedDashboardTeacherRoute,
  AuthenticatedDashboardPaymentCallbackRoute:
    AuthenticatedDashboardPaymentCallbackRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  ParentPortalRoute: ParentPortalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentLifeRoute: StudentLifeRoute,
  StudentPortalRoute: StudentPortalRoute,
  AcademicsNurseryRoute: AcademicsNurseryRoute,
  AcademicsPrimaryRoute: AcademicsPrimaryRoute,
  AcademicsSecondaryRoute: AcademicsSecondaryRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
